Added 'align-items' Section, Updated CSS & JS
fahdi/css-visual-learner pull request #19
Opened 2023-11-23 19:19 UTC by imran-khani

Added the 'align-items' section to the Flexbox visualizer, updated CSS for styling, and wrote JavaScript to handle 'align-items' changes independently.

**### Changes**:

**HTML**:

Added 'align-items' section with select options in flex-box.html.

**CSS**:
Updated styles in style.css and flexbox.css for the new section.

**JavaScript**:
Implemented event listener in flexbox.js to update the 'align-items' property dynamically.

**Reasoning**:
Enhances Flexbox visualizer by allowing users to experiment with 'align-items' options, offering an interactive learning experience.

Reviewer Notes:
Please review the 'align-items' section functionality, CSS consistency, and responsiveness.

2023-11-23 19:23 UTC, fahdi requested changes
Keep the original formatting.

2023-11-23 19:23 UTC, fahdi commented on flex-box.html
> +      name="description"
Keep the original formatting for meta fields.

2023-11-23 19:23 UTC, fahdi commented on flex-box.html
> -    <meta property="og:image" content="https://fahdi.github.io/css-visual-learner/thumbnails/css-visual-learner.jpg">
Keep the original meta formatting.

2023-11-23 19:26 UTC, imran-khani commented on flex-box.html
> -    <meta property="og:image" content="https://fahdi.github.io/css-visual-learner/thumbnails/css-visual-learner.jpg">
I didn't change the metadata. it is just because of formatting. nothing additional is touched except the addition of the align-items section

2023-11-23 19:32 UTC, fahdi commented on flex-box.html
> -    <meta property="og:image" content="https://fahdi.github.io/css-visual-learner/thumbnails/css-visual-learner.jpg">
But it updated the formatting which needs to be reverted in a commit.

2023-11-23 19:34 UTC, fahdi commented on flex-box.html
> -    <meta property="og:image" content="https://fahdi.github.io/css-visual-learner/thumbnails/css-visual-learner.jpg">
And you also have to resolve merge conflicts.

2023-11-24 13:41 UTC, fahdi approved these changes

2023-11-24 14:45 UTC, fahdi requested changes
Sidebar, menu items have been removed, please add them back in. You can pull the upstream main to see!

2023-11-24 14:45 UTC, fahdi commented on flex-box.html
> +                <li><a href="index.html">Home</a></li>
@imran-khani Please see that you don't remove the existing things, in this instance, you have removed menu items from the sidebar.

2023-11-24 15:32 UTC, closed without merging